### ISSUE TITLE
Are contributions allowed? 

### ISSUE THREAD

**Issue by simeon4real** [InjectiveLabs/website#23]
Not really an issue. I want to ask if contributions are allowed?

Even if it's just to `update readme`, `tech docs` or even `centering a div` on the website.

I'm currently looking to contribute to open source projects in the little way I can.

**Comment by ericxor61a0c0d** [comment]
Hey @simeon4real you're always welcome to! Just submit a pull request on our current public repos and we can review them

**Comment by simeon4real** [comment]
Thanks for your swift response
